[package]
name = "editor"
version = "0.1.0"
authors = ["Southclaws <accounts@southcla.ws>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
three-d = { path = "./three-d" }
log = "0.4"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
console_log = "0.1"
tri-mesh = "0.5.0"
